# Generated by Django 3.2 on 2021-04-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Second_losers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_data', models.DateField(db_index=True)),
                ('score', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logic.players')),
            ],
        ),
    ]
